# Esse workflow verifica os links dos arquivos se estão ok
name: Verifica links do site on pull requests

on: [pull_request]

jobs:
  # Verifica Link job
  link_checker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install Link Checker
        run: sudo apt-get install linkchecker
      - name: Run Link Checker
        run: linkchecker https://mrpsychoo.github.io/MrPsychoo2.github.io/
      - name: Check links in Markdown files
        run: linkchecker --file-output=csv --verbose --check-extern markdown/*.md
